@url_dev=http://localhost:3052/v1/api

POST {{url_dev}}/shop/sign-up
Content-Type: application/json
x-api-key: e1c293d2f761a07d112d4cafa360b576b40761634b14bd378210f650fa98c8edde2c922eb6344b69dbd36c7dc4f573fb970a48d955fdb490dd7568606f362b8a

{
    "name": "Shop JS 02",
    "email": "a@gmail06.com",
    "password": "abc123"
}

###
POST {{url_dev}}/shop/login
Content-Type: application/json
x-api-key: e1c293d2f761a07d112d4cafa360b576b40761634b14bd378210f650fa98c8edde2c922eb6344b69dbd36c7dc4f573fb970a48d955fdb490dd7568606f362b8a

{
    "name": "Shop JS 02",
    "email": "a@gmail06.com",
    "password": "abc123"
}

###
POST {{url_dev}}/shop/logout
Content-Type: application/json
x-api-key: e1c293d2f761a07d112d4cafa360b576b40761634b14bd378210f650fa98c8edde2c922eb6344b69dbd36c7dc4f573fb970a48d955fdb490dd7568606f362b8a
x-client-id: 6501d2f4873078dc84f6f6eb
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiI2NTAxZDJmNDg3MzA3OGRjODRmNmY2ZWIiLCJlbWFpbCI6ImFAZ21haWwwNi5jb20iLCJpYXQiOjE2OTQ2MjM2NTQsImV4cCI6MTY5NDc5NjQ1NH0.QTOXtvdQVjMCcBodSIYHCz5jKJYRfTiC1t5oq9rAPmRB768vNvOK2HVFsTJLZxpukn-vuIBIiqWEYbCtVbMUlb9mDYPtGJCCQh9q3haMO_iIBWLzaIbAdkYsL16Zp3-T8xTZA1L72AiWPr9YuAutGXaiJw0muPlG88JmAaM9q85FaJyBWmylJiSQnOXvPI6FAoGXy7BABN1Dg_QLP0cAfKvDBHFYodAj1sYvOHxW9dmVeaWiorp1PxoQPcwBVeiQvtZLFN-11wtfvFC3ZoSNrLFdDmj-KGgVW3Gi1oVZ6eXBemRqIe6wjFoC2Rnb23nChxaoI4CAPQeqjwS_ukyWxtbUFx-tim53bOdr7cp-RgPD-83IGyjdxhjcMY1ifTifBAcaLkQGfhNvl9470laDpkyOCL6DJHNEg-85DlgBH9F2PpxDPLu9CuYMKKxRjapDpARr6hztJP7tkWcN6iL5qjMd7mUUOe3ryWjA_alSEYSeZrQLzulcRot71i4xVJvYElYIUIBEOV_yVfNJ4nxZia92AeIJuOWUigRWRce5GUMtENc1CNtUJXLm2W8VGv_aO2YDDzukM40hg9zTKTUd2jQUKlhHxtzXGU3a7KOinLEV7LInfsfMR9Ahr34SkQwfFSeGaGZEakp7POlJIBWuJhWqsXoJFgoygwSgy1YztRM

{
    
}